Script started on Mon Oct  7 22:13:07 2024
[1m[7m%[27m[1m[0m                                                                                                                                                                                                          [0m[27m[24m[Ja.kamboj@Aryans-MacBook contacts % [K[?2004hssource v con
[Jconfig_data*              config_data5.34*          contacts_venvbinactivate  convertfilestops@         convertsegfilestopdf@     converttopdf@             
config_data5.30*          contacts_venv/            convertfilestopdf@        convertformat@            convertsegfilestops@      converttops@              [A[A[0m[27m[24m[35Csource con[Kfig_data5.304[12Dtacts_venv[1m/[0m [0m/bin[1m/[0m[0m/activate[?2004l
[J[1m[7m%[27m[1m[0m                                                                                                                                                                                                          [0m[27m[24m[J(contacts_venv) a.kamboj@Aryans-MacBook contacts % [K[?2004huuvicorn a main:app --reload[?2004l
[32mINFO[0m:     Will watch for changes in these directories: ['/Users/a.kamboj/programming/python/contacts']
[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     Started reloader process [[36m[1m5486[0m] using [36m[1mWatchFiles[0m
[32mINFO[0m:     Started server process [[36m5488[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     127.0.0.1:53773 - "[1mDELETE /v1/employee/6 HTTP/1.1[0m" [31m403 Forbidden[0m
[32mINFO[0m:     127.0.0.1:53775 - "[1mPOST /v1/auth/login HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:53777 - "[1mDELETE /v1/employee/6 HTTP/1.1[0m" [91m500 Internal Server Error[0m
[(3,)] []
[32mINFO[0m:     127.0.0.1:53846 - "[1mDELETE /v1/employee/32 HTTP/1.1[0m" [91m500 Internal Server Error[0m
[33mWARNING[0m:  WatchFiles detected changes in 'src/routers/employee_router.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5488[0m]
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 3, in <module>
    from src.routers.employee_router import employee_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/employee_router.py", line 41
    else:
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 40
[33mWARNING[0m:  WatchFiles detected changes in 'src/routers/employee_router.py'. Reloading...
[32mINFO[0m:     Started server process [[36m5601[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[(3,)] []
[32mINFO[0m:     127.0.0.1:53850 - "[1mDELETE /v1/employee/32 HTTP/1.1[0m" [91m500 Internal Server Error[0m
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5601[0m]
[32mINFO[0m:     Started server process [[36m5701[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[(3,)] []
[32mINFO[0m:     127.0.0.1:53921 - "[1mDELETE /v1/employee/32 HTTP/1.1[0m" [32m204 No Content[0m
[(1,), (14,), (14,)] [(7,), (14,), (32,)]
[32mINFO[0m:     127.0.0.1:53986 - "[1mDELETE /v1/employee/3 HTTP/1.1[0m" [32m204 No Content[0m
[(3,)] [(32,), (17,)]
[32mINFO[0m:     127.0.0.1:54051 - "[1mDELETE /v1/employee/14 HTTP/1.1[0m" [32m204 No Content[0m
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5701[0m]
[32mINFO[0m:     Started server process [[36m5786[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5786[0m]
[32mINFO[0m:     Started server process [[36m5851[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m5851[0m]
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
Process SpawnProcess-7:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 2, in <module>
    from src.routers.auth_router import auth_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/auth_router.py", line 6, in <module>
    from ..auth import Auth
  File "/Users/a.kamboj/programming/python/contacts/src/auth.py", line 7, in <module>
    from .entities.admin.admin import Admin
  File "/Users/a.kamboj/programming/python/contacts/src/entities/admin/admin.py", line 90
    reporting_employees = map(reporting_employees
                             ^
SyntaxError: '(' was never closed
Process SpawnProcess-8:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 2, in <module>
    from src.routers.auth_router import auth_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/auth_router.py", line 6, in <module>
    from ..auth import Auth
  File "/Users/a.kamboj/programming/python/contacts/src/auth.py", line 7, in <module>
    from .entities.admin.admin import Admin
  File "/Users/a.kamboj/programming/python/contacts/src/entities/admin/admin.py", line 90
    reporting_employees = map(reporting_employees
                             ^
SyntaxError: '(' was never closed
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
Process SpawnProcess-9:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 2, in <module>
    from src.routers.auth_router import auth_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/auth_router.py", line 6, in <module>
    from ..auth import Auth
  File "/Users/a.kamboj/programming/python/contacts/src/auth.py", line 7, in <module>
    from .entities.admin.admin import Admin
  File "/Users/a.kamboj/programming/python/contacts/src/entities/admin/admin.py", line 90
    reporting_employees = map(lambda reporting_employee:reporting_employee[0] reporting_employees
                             ^
SyntaxError: '(' was never closed
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Started server process [[36m6053[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6053[0m]
[32mINFO[0m:     Started server process [[36m6166[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
3 <map object at 0x105b26920>
[32mINFO[0m:     127.0.0.1:54178 - "[1mDELETE /v1/employee/14 HTTP/1.1[0m" [32m204 No Content[0m
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6166[0m]
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
Process SpawnProcess-12:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 2, in <module>
    from src.routers.auth_router import auth_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/auth_router.py", line 6, in <module>
    from ..auth import Auth
  File "/Users/a.kamboj/programming/python/contacts/src/auth.py", line 7, in <module>
    from .entities.admin.admin import Admin
  File "/Users/a.kamboj/programming/python/contacts/src/entities/admin/admin.py", line 90
    reporting_employees = list(map(lambda reporting_employee:reporting_employee[0], reporting_employees)
                              ^
SyntaxError: '(' was never closed
Process SpawnProcess-13:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 2, in <module>
    from src.routers.auth_router import auth_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/auth_router.py", line 6, in <module>
    from ..auth import Auth
  File "/Users/a.kamboj/programming/python/contacts/src/auth.py", line 7, in <module>
    from .entities.admin.admin import Admin
  File "/Users/a.kamboj/programming/python/contacts/src/entities/admin/admin.py", line 90
    reporting_employees = list(map(lambda reporting_employee:reporting_employee[0], reporting_employees)
                              ^
SyntaxError: '(' was never closed
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Started server process [[36m6282[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
3 [32, 17]
[32mINFO[0m:     127.0.0.1:54183 - "[1mDELETE /v1/employee/14 HTTP/1.1[0m" [32m204 No Content[0m
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6282[0m]
[32mINFO[0m:     Started server process [[36m6348[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6348[0m]
[32mINFO[0m:     Started server process [[36m6464[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6464[0m]
[32mINFO[0m:     Started server process [[36m6544[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6544[0m]
[32mINFO[0m:     Started server process [[36m6577[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6577[0m]
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Started server process [[36m6642[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Started server process [[36m6659[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6659[0m]
[32mINFO[0m:     Started server process [[36m6724[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6724[0m]
Process SpawnProcess-22:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 2, in <module>
    from src.routers.auth_router import auth_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/auth_router.py", line 6, in <module>
    from ..auth import Auth
  File "/Users/a.kamboj/programming/python/contacts/src/auth.py", line 7, in <module>
    from .entities.admin.admin import Admin
  File "/Users/a.kamboj/programming/python/contacts/src/entities/admin/admin.py", line 101
    write_to_table("relations",)
    ^^^^^^^^^^^^^^
IndentationError: expected an indented block after 'for' statement on line 100
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Started server process [[36m6791[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6791[0m]
[32mINFO[0m:     Started server process [[36m6868[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6868[0m]
[32mINFO[0m:     Started server process [[36m6958[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m6958[0m]
[32mINFO[0m:     Started server process [[36m7024[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7024[0m]
Process SpawnProcess-27:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 2, in <module>
    from src.routers.auth_router import auth_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/auth_router.py", line 6, in <module>
    from ..auth import Auth
  File "/Users/a.kamboj/programming/python/contacts/src/auth.py", line 7, in <module>
    from .entities.admin.admin import Admin
  File "/Users/a.kamboj/programming/python/contacts/src/entities/admin/admin.py", line 101
    write_to_table("relations",{"employee":emp,"reports_to"})
                                                          ^
SyntaxError: ':' expected after dictionary key
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Started server process [[36m7124[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7124[0m]
[32mINFO[0m:     Started server process [[36m7213[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7213[0m]
[32mINFO[0m:     Started server process [[36m7324[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7324[0m]
[32mINFO[0m:     Started server process [[36m7357[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7357[0m]
[32mINFO[0m:     Started server process [[36m7416[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7416[0m]
Process SpawnProcess-33:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 2, in <module>
    from src.routers.auth_router import auth_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/auth_router.py", line 6, in <module>
    from ..auth import Auth
  File "/Users/a.kamboj/programming/python/contacts/src/auth.py", line 7, in <module>
    from .entities.admin.admin import Admin
  File "/Users/a.kamboj/programming/python/contacts/src/entities/admin/admin.py", line 100
    for in reporting_employees:
        ^^
SyntaxError: invalid syntax
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
Process SpawnProcess-34:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 2, in <module>
    from src.routers.auth_router import auth_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/auth_router.py", line 6, in <module>
    from ..auth import Auth
  File "/Users/a.kamboj/programming/python/contacts/src/auth.py", line 7, in <module>
    from .entities.admin.admin import Admin
  File "/Users/a.kamboj/programming/python/contacts/src/entities/admin/admin.py", line 100
    for reporting_employeein reporting_employees:
                             ^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Started server process [[36m7580[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7580[0m]
Process SpawnProcess-36:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a.kamboj/programming/python/contacts/contacts_venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/a.kamboj/programming/python/contacts/main.py", line 2, in <module>
    from src.routers.auth_router import auth_router
  File "/Users/a.kamboj/programming/python/contacts/src/routers/auth_router.py", line 6, in <module>
    from ..auth import Auth
  File "/Users/a.kamboj/programming/python/contacts/src/auth.py", line 7, in <module>
    from .entities.admin.admin import Admin
  File "/Users/a.kamboj/programming/python/contacts/src/entities/admin/admin.py", line 100
    for  in reporting_employees:
         ^^
SyntaxError: invalid syntax
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Started server process [[36m7718[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7718[0m]
[32mINFO[0m:     Started server process [[36m7815[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7815[0m]
[32mINFO[0m:     Started server process [[36m7873[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7873[0m]
[32mINFO[0m:     Started server process [[36m7945[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m7945[0m]
[32mINFO[0m:     Started server process [[36m8002[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m8002[0m]
[32mINFO[0m:     Started server process [[36m8088[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m8088[0m]
[32mINFO[0m:     Started server process [[36m8155[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[33mWARNING[0m:  WatchFiles detected changes in 'src/entities/admin/admin.py'. Reloading...
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Waiting for application shutdown.
[32mINFO[0m:     Application shutdown complete.
[32mINFO[0m:     Finished server process [[36m8155[0m]
[32mINFO[0m:     Started server process [[36m8216[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
